config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"
  get "pages/about"

  resources :teams
  resources :teams do
    resources :scarves, only: [:new, :create, :destroy] 
  end
  
  resources :scarves, only: [:show, :index]
  
  devise_for :users

  resources :users, only: [:index, :show, :destroy]

  resources :users do
    resources :photos
  end

  resources :teamss do
    resources :photos
  end

  resources :scarves do
    resources :photos
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/scarf.rb
class Scarf < ActiveRecord::Base
	belongs_to :user
	
	belongs_to :team
	has_many :photos, as: :imageable
end

app/models/team.rb
class Team < ActiveRecord::Base

	has_many :scarves
	has_many :users
	has_many: :photos, as: :imageable
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :scarves
	has_many :teams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
	  def configure_permitted_parameters
	  	registration_params = [:full_name, :scarf, :team, :email, :password, :password_confirmation]
	  	devise_parameter_sanitizer.for(:sign_up) << :phone
	  end
end

app/controllers/pages_controller.rb
class  PagesController < ApplicationController

	def index
	end

	def about		
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	  before_filter :authenticate_user!

	def index
		@photos = Photo.all
	end
	
	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			redirect_to photo_path, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	def show
		@photo = Photo.find_by_id(params[:id])
	end

	def destroy
		@photo = Photo.find params[:id]
		@photo.destroy
		flash[:notice] = "photo successfully deleted."
		redirect_to root_path
	end

	private
	
	def photo_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/scarves_controller.rb
class ScarvesController < ApplicationController
  before_action :set_scarf, only: [:show, :edit, :update, :destroy]

  # GET /scarves
  # GET /scarves.json
  def index
    @scarves = Scarf.all
  end

  # GET /scarves/1
  # GET /scarves/1.json
  def show
  end

  # GET /scarves/new
  def new
    @scarf = Scarf.new
  end

  # GET /scarves/1/edit
  def edit
  end

  # POST /scarves
  # POST /scarves.json
  def create
    @scarf = Scarf.new(scarf_params)

    respond_to do |format|
      if @scarf.save
        format.html { redirect_to @scarf, notice: 'Scarf was successfully created.' }
        format.json { render :show, status: :created, location: @scarf }
      else
        format.html { render :new }
        format.json { render json: @scarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scarves/1
  # PATCH/PUT /scarves/1.json
  def update
    respond_to do |format|
      if @scarf.update(scarf_params)
        format.html { redirect_to @scarf, notice: 'Scarf was successfully updated.' }
        format.json { render :show, status: :ok, location: @scarf }
      else
        format.html { render :edit }
        format.json { render json: @scarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scarves/1
  # DELETE /scarves/1.json
  def destroy
    @scarf.destroy
    respond_to do |format|
      format.html { redirect_to scarves_url, notice: 'Scarf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scarf
      @scarf = Scarf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scarf_params
      params.require(:scarf).permit(:title, :description, :club_id, :user_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  before_filter :authenticate_user!

	def index
		@users = User.all
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	def show
		@scarves = Scarves.all 
		@user = User.find_by_id(params[:id])
	end

	def destroy
		@user = User.find params[:id]
		@user.destroy
		flash[:notice] = "User successfully deleted."
		redirect_to root_path
	end

	private
	
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
	    base_title = "Scarf.ly // A community of soccer neckwear enthusiasts"
	    if page_title.empty?
	      base_title
	    else
	      "#{base_title} | #{page_title}"
	    end
	  end
end

app/helpers/scarves_helper.rb
module ScarvesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	  <%= csrf_meta_tags %>
	  
	</head>
	<body>
		<div class="container box first"> 
		<%= flash[:notice] %>
			<div class="aboutlinks">
				<ul>
			  		<li><%= link_to 'Home', root_path %></li>
			  		<% if user_signed_in? %>
			  		  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
			  		  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
			  		<% else %>
			  		  <li><%= link_to 'Sign in', new_user_session_path %></li>
			  		  <li><%= link_to 'Sign up', new_user_registration_path %></li>
			  		<% end %>
			  		<li><a href="pages/about.html">About</a></li>
			    	<li><a href="mailto:adam@scarf.ly">Contact</a></li>
			  	</ul>
			 </div>		 
			 <%= yield %>
		</div>
		<%= render :partial => 'layouts/ga' if Rails.env.production? %>


	</body>
</html>

app/views/layouts/partial _ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54227239-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pages/about.html.erb
<div class="box">
	<div class="aboutlinks">
		<ul>
	  		<% if user_signed_in? %>
	  		  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	  		  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	  		<% else %>
	  		  <li><%= link_to 'Sign in', new_user_session_path %></li>
	  		  <li><%= link_to 'Sign up', new_user_registration_path %></li>
	  		<% end %>
	  		<li><a href="pages/about.html">About</a></li>
	    	<li><a href="mailto:adam@scarf.ly">Contact</a></li>
	  	</ul>
	 </div>
	<h1>About</h1>

	<p><span class="title">What is Scarf.ly?</span>Scarf.ly is a place for soccer neckwear enthusiasts to explore, browse, and trade scarfs with other like-minded fans. You'll be able to catalog and add photos of your collection, learn the stories behind your favorite editions, add scarfs you desire to a wishlist, and send messages to other scarf fans to help faciliate trades and exchanges.</p>&nbsp;
	<p><span class="title">Seriously?</span>Yup.</p>&nbsp;
	<p><span class="title">How can I help?</span>Interested developers and designers, and anyone else, please <a href="mailto:adam@scarf.ly">contact me</a> to help out.<br><br>Check out our <a href="http://twitter.com/go_scarfly">Twitter feed @go_scarfly</a> to stay up to date with our development, drop us a suggestion, or whatever else you want.. </p>&nbsp;
</div>
		<%= render :partial => 'layouts/ga' if Rails.env.production? %>

<!--
BEGIN FOOTER
AREA HERE
-->


<!--
END PAGE CONTENT
ABOVE
-->

app/views/pages/index.html.erb
	<h1>Scarf.ly</h1>
	  <h2>A community of discerning soccer neckwear enthusiasts.</h2>
	  <h3><a href="https://twitter.com/search?q=%23showusyourscarf%20since%3A2014-08-01&src=typd">#showusyourscarf</a></h3>
	
	  <p><a href="https://api.venmo.com/v1/oauth/authorize?client_id=CLIENT_ID&scope=make_payments%20access_profile">TEst</p>
	<div class="row-fluid">
		  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<div class="box-color">  
			  	<h3><%= link_to 'Explore:', scarves_path %></h3>
			  	<p>Browse the Scarf.ly gallery and easily researchand discover your favorite club's scarves!
			  	</p>
		 	</div>
		 </div>

		  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
		  	<div class="box-color"> 
		  		<h3>Register:</h3>
		  		<p>Sign up and join us! Show the football world the scarves you have collected and which you would like to acquire. </p>
		 	</div>
		 </div>
	</div>
		<%= render :partial => 'layouts/ga' if Rails.env.production? %>

app/views/scarves/_form.html.erb
<%= form_for(@scarf) do |f| %>
  <% if @scarf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scarf.errors.count, "error") %> prohibited this scarf from being saved:</h2>

      <ul>
      <% @scarf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :club_id, value: club.id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scarves/edit.html.erb
<h1>Editing scarf</h1>

<%= render 'form' %>

<%= link_to 'Show', @scarf %> |
<%= link_to 'Back', scarves_path %>

app/views/scarves/index.html.erb
<h1>Listing scarves</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Club</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scarves.each do |scarf| %>
      <tr>
        <td><%= scarf.title %></td>
        <td><%= scarf.description %></td>
        <td><%= scarf.club_id %></td>
        <td><%= scarf.user_id %></td>
        <td><%= link_to 'Show', scarf %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/scarves/new.html.erb
<h1>New scarf</h1>

<%= render 'form' %>

<%= link_to 'Back', scarves_path %>

app/views/scarves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scarf.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scarf.description %>
</p>

<p>
  <strong>Club:</strong>
  <%= @scarf.club_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @scarf.user_id %>
</p>

<%= link_to 'Back', scarves_path %>

app/views/users/index.html.erb
<ul>
	<% User.all.each do |user| %>
		<li><%= link_to "#{user.email}", user_path(user) %></li>
		<li><% user.id.to_s %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
new.html.erb

app/views/users/show.html.erb
this is where it is going????

<h1><%= @user.email %></h1>

<% @scarves.each do |sc|%>
	sc.user
<%end%>
<%= link_to "Home", root_path %>